#!/usr/bin/env bash
set -e

source $SNAP/actions/common/utils.sh

KUBECTL="$SNAP/microk8s-kubectl.wrapper"
HELM="$SNAP/microk8s-helm.wrapper"
echo "Disabling EBS driver"

$KUBECTL delete storageclass ebs-sc
$KUBECTL delete secret aws-secret --namespace kube-system
# unload the the manifests
$HELM delete aws-ebs-csi-driver -n kube-system > /dev/null 2>&1

echo "EBS driver has been disabled."