#!/usr/bin/env bash
set -e

source $SNAP/actions/common/utils.sh

KUBECTL="$SNAP/microk8s-kubectl.wrapper"
HELM="$SNAP/microk8s-helm.wrapper"
echo "Disabling EFS driver"

$KUBECTL delete storageclass efs-sc
# unload the the manifests
$HELM delete aws-efs-csi-driver -n kube-system > /dev/null 2>&1

echo "EFS driver has been disabled."