#!/usr/bin/env bash
set -e

source $SNAP/actions/common/utils.sh
CURRENT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
source $CURRENT_DIR/../common/utils.sh

usage() { echo "Usage: sudo microk8s enable aws-efs-csi-driver [-i <filesystem_id>]" 1>&2; exit 1; }

while getopts ":i:" o; do
    case "${o}" in
        i)
            FSID=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${FSID}" ]; then
    usage
fi

"$SNAP/microk8s-enable.wrapper" core/helm3

HELM="${SNAP}/microk8s-helm3.wrapper"

echo "Enabling EFS driver"

$HELM repo add aws-efs-csi-driver https://canonical.github.io/aws-efs-csi-driver
$HELM repo update

$HELM upgrade --install aws-efs-csi-driver --set node.kubeletPath=/var/snap/microk8s/common/var/lib/kubelet \
  --set node.efsStatePath=/var/snap/microk8s/common/run/efs \
  --set node.efsUCPath=/var/snap/microk8s/common/run/amazon/efs \
  --set node.efsLegacyUCPath=/var/snap/microk8s/common/etc/amazon/efs \
  --namespace kube-system aws-efs-csi-driver/aws-efs-csi-driver
declare -A map
map[\$FSID]="$FSID"
use_addon_manifest aws-efs-csi-driver/storageclass apply "$(declare -p map)"

echo "EFS driver has been enabled."
