#!/usr/bin/env bash
set -e

source $SNAP/actions/common/utils.sh
CURRENT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

"$SNAP/microk8s-enable.wrapper" core/helm3

NAMESPACE_PTR="observability"
KUBECTL="$SNAP/microk8s-kubectl.wrapper"
HELM="${SNAP}/microk8s-helm3.wrapper"

echo "Enabling EFS driver"

$HELM repo add aws-efs-csi-driver https://kubernetes-sigs.github.io/aws-efs-csi-driver
$HELM repo update

read -ra ARGUMENTS <<< "$1"
if [[ ! -z "${ARGUMENTS[@]}" ]]
then
  serviceaccount="${ARGUMENTS[@]}"
else
  serviceaccount="none"
fi

if [[ $serviceaccount == "none" ]]
then
    $HELM upgrade --install aws-efs-csi-driver --namespace kube-system aws-efs-csi-driver/aws-efs-csi-driver
else
    $HELM upgrade --install aws-efs-csi-driver --namespace kube-system aws-efs-csi-driver/aws-efs-csi-driver --set controller.serviceAccount.name=$serviceaccount
fi

echo "EFS driver has been enabled."
