#!/usr/bin/env bash
set -e

source $SNAP/actions/common/utils.sh
CURRENT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
source $CURRENT_DIR/../common/utils.sh

usage() { echo "Usage: sudo microk8s enable aws-efs-csi-driver [-i <filesystem_id>]" 1>&2; exit 1; }

while getopts ":i:" o; do
    case "${o}" in
        i)
            FSID=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${FSID}" ]; then
    usage
fi

"$SNAP/microk8s-enable.wrapper" core/helm3

KUBECTL="$SNAP/microk8s-kubectl.wrapper"
HELM="${SNAP}/microk8s-helm3.wrapper"

echo "Enabling EFS driver"

$HELM repo add aws-efs-csi-driver https://kubernetes-sigs.github.io/aws-efs-csi-driver
$HELM repo update

$HELM upgrade --install aws-efs-csi-driver --namespace kube-system aws-efs-csi-driver/aws-efs-csi-driver
declare -A map
map[\$FSID]="$FSID"
use_addon_manifest aws-efs-csi-driver/storageclass apply "$(declare -p map)"

$KUBECTL patch ds efs-csi-node --patch-file aws-efs-csi-driver/node-ds-patch.yaml

echo "EFS driver has been enabled."
