name: Run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-setuptools nfs-common
          sudo pip3 install --upgrade pip
          sudo pip3 install -U pytest sh
      - name: Running addons tests
        run: |
          set -x
          sudo snap install microk8s --classic --channel=latest/edge
          sudo microk8s status --wait-ready --timeout 600
          sudo microk8s addons repo add aws .
          export UNDER_TIME_PRESSURE="True"
          export SKIP_PROMETHEUS="False"
          sudo -E pytest -s -ra ./tests/test-addons.py
          sudo snap remove microk8s --purge
      - name: Running addons tests on strict
        run: |
          set -x
          sudo snap install microk8s --channel=latest/edge/strict
          sudo microk8s status --wait-ready --timeout 600
          sudo microk8s addons repo add aws .
          export UNDER_TIME_PRESSURE="True"
          export SKIP_PROMETHEUS="False"
          export STRICT="yes"
          sudo -E pytest -s -ra ./tests/test-addons.py
          sudo snap remove microk8s --purge
